DIS-79: Modify installation template script to also perform an upgrade when the application already exists

diff --git a/appcli/templates/installer.j2 b/appcli/templates/installer.j2
--- a/appcli/templates/installer.j2
+++ b/appcli/templates/installer.j2
@@ -17,19 +17,26 @@ function main()
 
     cd "{{ install_dir }}"
 
+    # Create versioned launcher
     local _launcher_versioned=".{{ cli_context.app_name|lower }}-{{ cli_context.app_version }}"
     generate_launcher > "${_launcher_versioned}" || print_error_and_exit "No permissions to write to [${_launcher_versioned}]"
     chmod a+x "${_launcher_versioned}"
 
+    # Create date-based launcher link
     local _launcher_deploy_date=".$(date -Isec --utc)"
     rm -f "${_launcher_deploy_date}" || print_error_and_exit "No permissions to delete to [${_launcher_deploy_date}]"
     ln -s "${_launcher_versioned}" "${_launcher_deploy_date}"
 
     local _launcher_generic="{{ cli_context.app_name|lower }}"
+
+    # If the generic launcher already exists, upgrade the existing application
+    [[ -e "${_launcher_generic}" ]] && upgrade_existing_application "${_launcher_generic}" "${_launcher_versioned}"
+
+    # Update the symlink to the generic launcher
     rm -f "${_launcher_generic}" || print_error_and_exit "No permissions to delete to [${_launcher_generic}]"
     ln -s "${_launcher_versioned}" "${_launcher_generic}"
 
-    cat <<EOF
+    >&2 cat <<EOF
     $(date -Isec --utc) INFO: {{ cli_context.app_name|lower }} version [{{ cli_context.app_version }}] can be launched via:
 
         {{ install_dir }}/{{ cli_context.app_name|lower }}
@@ -61,9 +68,25 @@ function generate_launcher()
             launcher
 }
 
+function upgrade_existing_application()
+{
+    local _launcher_existing="$(realpath ${1})"
+    local _launcher_upgrade="$(realpath ${2})"
+
+    >&2 echo "Installing an upgrade on existing application..."
+
+    # Stop services and apply with the old launcher
+    NO_TTY=true ${_launcher_existing} service stop
+    NO_TTY=true ${_launcher_existing} configure apply --force
+
+    # Migrate and apply with the new launcher
+    NO_TTY=true ${_launcher_upgrade} migrate
+    NO_TTY=true ${_launcher_upgrade} configure apply --force
+}
+
 function print_error_and_exit()
 {
-    echo "$(date -Isec --utc) ERROR: $@"
+    >&2 echo "$(date -Isec --utc) ERROR: $@"
     exit 1
 }
 
